builders:
  json_widget:
    import: "package:r_flutter/builder.dart"
    builder_factories:
      - "builder"
    build_extensions: {".json": [".dart"]}
    auto_apply: root_package
    build_to: cache
    defaults:
      generate_for:
        include:
          - lib/**